// ============================================================
// AI视频分区的数据 —— 改这个文件就能更新 aivideo.html
// （渲染在 aivideo-render.js 里，两个文件都只在「AI视频」那一页加载）
//
// ★ 你只需要动下面那个数组 ★
//
// 这一页是一条「LLM 发展时间线」：每个节点一条，你往 url 里填视频地址就行。
// 字段说明：
//   date   日期。"2017-06" 或 "2017-06-12" 这样写；只有年份就写 "2017"。
//          页面按日期从早到晚自动排，显示成 2017.06；空着会显示「时间待填写」
//   title  节点名（必填）
//   text   一到两句话说明这个节点是什么、为什么重要（必填）
//   tags   标签数组，纯展示。现用：论文 / 模型 / 产品 / 开源 / 中国 / 推理 / 多模态 / 智能体 / 视频 / 里程碑
//   url    ★ 你要填的：这个节点对应的视频地址（B站 / YouTube 都行，必须 http(s) 开头）。
//          留空 → 页面显示灰色「待填视频」，不会有死链
//   source 资料来源链接（可溯源用；留空就不显示）。填了页面上会有一个小的「来源 ↗」
//
// 想加节点就复制一段改字段；不想要哪条就整段删掉。
// 时间线来自公开资料整理（2026-09-29 核查过每条来源链接），年份/日期以来源页为准。
// ============================================================

window.AIVIDEO_TIMELINE = [
  {
    date: "2017-06-12",
    title: "Transformer 论文",
    text: "Google 团队发表《Attention Is All You Need》，提出完全基于自注意力机制的 Transformer 架构，抛弃循环与卷积，训练高度可并行，成为此后几乎所有大语言模型的底座。",
    tags: ["论文", "里程碑"],
    url: '',
    source: "https://arxiv.org/abs/1706.03762",
  },
  {
    date: "2018-06-11",
    title: "GPT-1 发布",
    text: "OpenAI 发表 GPT-1，用 1.17 亿参数的解码器式 Transformer 先做无监督预训练再做微调迁移，首次验证「预训练＋微调」这条路线，是 GPT 系列的起点。",
    tags: ["模型", "论文"],
    url: '',
    source: "https://openai.com/index/language-unsupervised/",
  },
  {
    date: "2018-10-11",
    title: "BERT 发布",
    text: "Google 发布 BERT，用双向编码器做掩码语言建模，在 11 项自然语言理解任务上刷新纪录。它把预训练范式推向主流，此后两年 NLP 几乎被 BERT 变体占据。",
    tags: ["论文", "模型"],
    url: '',
    source: "https://arxiv.org/abs/1810.04805",
  },
  {
    date: "2019-02-14",
    title: "GPT-2 发布",
    text: "OpenAI 发布 15 亿参数的 GPT-2，展示零样本能力，并因担心滥用而分阶段放出权重。这次「先发布、后开源」的争议，让语言模型的社会风险第一次进入公众讨论。",
    tags: ["模型"],
    url: '',
    source: "https://openai.com/index/better-language-models/",
  },
  {
    date: "2019-10-23",
    title: "T5",
    text: "Google 把各种自然语言任务统一成「文本到文本」的形式，并开源预训练模型，成为后来「一个模型干所有事」思路的代表作。",
    tags: ["论文", "开源"],
    url: '',
    source: "https://arxiv.org/abs/1910.10683",
  },
  {
    date: "2020-01-23",
    title: "缩放定律提出",
    text: "OpenAI 发表缩放定律论文，给出损失随参数量、数据量与算力按幂律下降的经验规律。它让「堆算力就能变强」从直觉变成可预测的工程指南，直接推动了大模型军备竞赛。",
    tags: ["论文", "里程碑"],
    url: '',
    source: "https://arxiv.org/abs/2001.08361",
  },
  {
    date: "2020-05-28",
    title: "GPT-3 发布",
    text: "OpenAI 发布 1750 亿参数的 GPT-3，首次证明无需微调，仅靠上下文里的几个示例（少样本学习）就能完成大量任务，是「大模型」这个概念真正成立的节点。",
    tags: ["模型", "里程碑"],
    url: '',
    source: "https://arxiv.org/abs/2005.14165",
  },
  {
    date: "2021-07-07",
    title: "Codex 与代码能力",
    text: "在 GPT-3 之上用代码继续训练的 Codex 证明大模型能写程序，直接催生了 GitHub Copilot 这类 AI 编程工具。",
    tags: ["模型", "产品"],
    url: '',
    source: "https://arxiv.org/abs/2107.03374",
  },
  {
    date: "2022-01",
    title: "InstructGPT 与 RLHF",
    text: "OpenAI 发表 InstructGPT，用人类反馈强化学习让模型学会遵循指令，1.3B 版本的输出被人类评审更偏好于 175B 的 GPT-3。这条对齐路线直接通向 ChatGPT。",
    tags: ["论文", "里程碑"],
    url: '',
    source: "https://openai.com/index/instruction-following/",
  },
  {
    date: "2022-04-04",
    title: "PaLM",
    text: "Google 的 5400 亿参数稠密模型，用 Pathways 系统训练，在推理与多语言任务上展示了「规模换能力」的上限。",
    tags: ["模型"],
    url: '',
    source: "https://arxiv.org/abs/2204.02311",
  },
  {
    date: "2022-11-30",
    title: "ChatGPT 上线",
    text: "OpenAI 以研究预览形式上线 ChatGPT，免费对话界面两周内吸引上百万用户，把大模型从论文与 API 推向大众。它被普遍视为生成式 AI 浪潮的引爆点。",
    tags: ["产品", "里程碑"],
    url: '',
    source: "https://openai.com/index/chatgpt/",
  },
  {
    date: "2023-02-24",
    title: "LLaMA 开源",
    text: "Meta 发布 LLaMA 系列权重，覆盖 7B 到 65B。虽限研究用途且随后遭泄露，但它让学术界与创业公司第一次能在本地跑出接近 GPT-3.5 的效果，催生开源微调生态。",
    tags: ["开源", "模型"],
    url: '',
    source: "https://en.wikipedia.org/wiki/LLaMA",
  },
  {
    date: "2023-03-14",
    title: "GPT-4 发布",
    text: "OpenAI 发布 GPT-4，支持图像输入，在律师资格考试、SAT 等专业测试中进入人类前 10%，推理与长文能力显著提升，成为此后一年多事实上的能力天花板。",
    tags: ["模型", "多模态"],
    url: '',
    source: "https://openai.com/index/gpt-4-research/",
  },
  {
    date: "2023-03-14",
    title: "Claude 初代发布",
    text: "Anthropic 发布初代 Claude，定位为通过宪法 AI 训练的对话助手，主打有用、诚实、无害与长上下文。它确立了 Claude 系列在安全对齐上的技术路线。",
    tags: ["产品", "模型"],
    url: '',
    source: "https://www.anthropic.com/news/introducing-claude",
  },
  {
    date: "2023-07-18",
    title: "Llama 2 发布",
    text: "Meta 与微软联合发布 Llama 2，7B/13B/70B 权重对商业使用开放，并配套发布安全微调版本。开源权重第一次能在商业场景正面对抗闭源 API，开源大模型浪潮由此加速。",
    tags: ["开源", "模型"],
    url: '',
    source: "https://en.wikipedia.org/wiki/Llama_2",
  },
  {
    date: "2023-08-03",
    title: "通义千问开源",
    text: "阿里巴巴开源通义千问 Qwen-7B，成为中国最早一批开放权重的大厂模型。此后 Qwen 以密集的版本迭代和宽松许可，逐步成长为全球下载量最大的开源模型家族之一。",
    tags: ["开源", "中国"],
    url: '',
    source: "https://en.wikipedia.org/wiki/Qwen",
  },
  {
    date: "2023-09-27",
    title: "Mistral 7B 发布",
    text: "法国 Mistral AI 发布 7.3B 的 Mistral 7B，以 Apache 2.0 许可开放，性能超过更大的 Llama 2 13B，证明高质量数据与小模型同样能打，欧洲开源阵营由此崛起。",
    tags: ["开源", "模型"],
    url: '',
    source: "https://mistral.ai/news/announcing-mistral-7b/",
  },
  {
    date: "2023-11-29",
    title: "DeepSeek 首次开源",
    text: "DeepSeek 开源首个自研大模型 DeepSeek-LLM（7B/67B），主打中英双语能力并公开训练细节，是这家中国公司进入开源大模型竞赛的起点。",
    tags: ["开源", "中国"],
    url: '',
    source: "https://github.com/deepseek-ai/DeepSeek-LLM",
  },
  {
    date: "2023-12-06",
    title: "Gemini 1.0 发布",
    text: "Google DeepMind 发布原生多模态模型 Gemini 1.0。它分 Ultra、Pro、Nano 三档，Ultra 在多项基准上超过 GPT-4，同时接入对话产品 Bard，标志 Google 把全线资源押注到 Gemini 品牌。",
    tags: ["多模态", "模型"],
    url: '',
    source: "https://blog.google/technology/ai/google-gemini-ai/",
  },
  {
    date: "2024-02-15",
    title: "Gemini 1.5 长上下文",
    text: "Google 发布 Gemini 1.5 Pro，基于 MoE 架构，把上下文窗口推高到 100 万 token，内部测试甚至达到 1000 万，超长上下文从此成为各家旗舰的标配指标。",
    tags: ["多模态", "里程碑"],
    url: '',
    source: "https://blog.google/technology/ai/google-gemini-next-generation-model-february-2024/",
  },
  {
    date: "2024-02-15",
    title: "Sora 亮相",
    text: "OpenAI 展示文生视频模型 Sora，能生成约一分钟连贯画面，AI 视频从「几秒动图」进入可用阶段，也成了这一页名字的由来。",
    tags: ["视频", "多模态"],
    url: '',
    source: "https://en.wikipedia.org/wiki/Sora_(text-to-video_model)",
  },
  {
    date: "2024-03-04",
    title: "Claude 3",
    text: "Claude 3 分 Haiku / Sonnet / Opus 三档，旗舰在多模态基准上超过当时的 GPT-4，「按能力分档定价」成为行业惯例。",
    tags: ["模型", "多模态"],
    url: '',
    source: "https://www.anthropic.com/news/claude-3-family",
  },
  {
    date: "2024-04-18",
    title: "Llama 3 发布",
    text: "Meta 发布 Llama 3 的 8B 与 70B 版本，训练数据量提升到 15T token，指令跟随与代码能力大幅改善，并以更宽松的社区许可开放，成为开源生态新的事实标准。",
    tags: ["开源", "模型"],
    url: '',
    source: "https://en.wikipedia.org/wiki/Llama_(language_model)",
  },
  {
    date: "2024-05-07",
    title: "DeepSeek-V2 与 MLA",
    text: "DeepSeek 发布并开源 V2，提出多头潜在注意力（MLA）与 DeepSeekMoE，把推理成本压到同级别模型的几分之一，同时带动国内 API 价格战，中国模型首次以效率取胜。",
    tags: ["中国", "开源"],
    url: '',
    source: "https://arxiv.org/abs/2405.04434",
  },
  {
    date: "2024-05-13",
    title: "GPT-4o 发布",
    text: "OpenAI 发布 GPT-4o，意为 omni，文本、图像、音频在同一模型中端到端处理，语音对话延迟接近真人，把多模态实时交互变成产品级体验。",
    tags: ["多模态", "产品"],
    url: '',
    source: "https://openai.com/index/hello-gpt-4o/",
  },
  {
    date: "2024-09-12",
    title: "OpenAI o1 发布",
    text: "OpenAI 发布 o1，用大规模强化学习训练模型在作答前先进行长链思考。这是首个被官方称为「推理模型」的大模型，把测试时算力扩展变成新的能力增长曲线。",
    tags: ["推理", "里程碑"],
    url: '',
    source: "https://openai.com/index/introducing-openai-o1-preview/",
  },
  {
    date: "2024-12-26",
    title: "DeepSeek-V3 发布",
    text: "DeepSeek 发布并开源 671B 的 V3，采用 MoE 架构、每个 token 仅激活 37B，训练成本约 557 万美元。它以极低算力达到闭源旗舰水平，震动整个行业。",
    tags: ["中国", "开源"],
    url: '',
    source: "https://api-docs.deepseek.com/news/news1226",
  },
  {
    date: "2025-01-20",
    title: "DeepSeek-R1 开源",
    text: "DeepSeek 发布 R1，首次公开证明纯强化学习即可激发推理能力，并以 MIT 许可开源权重。它引发全球对算力投入与开源路线的重估，一度导致美股科技板块剧烈波动。",
    tags: ["推理", "开源"],
    url: '',
    source: "https://api-docs.deepseek.com/news/news250120",
  },
  {
    date: "2025-02-24",
    title: "Claude 3.7 与 Code",
    text: "Anthropic 发布 Claude 3.7 Sonnet，首次把扩展思考与快速回答合并进同一模型，并同期推出命令行编程工具 Claude Code，AI 编程助手从此成为独立产品赛道。",
    tags: ["推理", "智能体"],
    url: '',
    source: "https://www.anthropic.com/news/claude-3-7-sonnet",
  },
  {
    date: "2025-03-25",
    title: "Gemini 2.5 发布",
    text: "Google 发布 Gemini 2.5 Pro，把「先思考再回答」内置为默认行为，并在推理与编程基准上登顶，同时提供百万级上下文，成为当年最强的闭源模型之一。",
    tags: ["推理", "模型"],
    url: '',
    source: "https://blog.google/technology/google-deepmind/gemini-model-thinking-updates-march-2025/",
  },
  {
    date: "2025-04-05",
    title: "Llama 4 发布",
    text: "Meta 发布 Llama 4 Scout 与 Maverick，采用 MoE 架构并原生多模态，Scout 宣称支持 1000 万 token 上下文。但社区对基准成绩争议较大，开源旗手的领先优势开始被追上。",
    tags: ["开源", "多模态"],
    url: '',
    source: "https://en.wikipedia.org/wiki/Llama_4",
  },
  {
    date: "2025-04-16",
    title: "o3 与 o4-mini",
    text: "OpenAI 正式上线 o3 与 o4-mini，把推理能力与联网搜索、图像分析、代码执行等工具调用结合，推理模型从单点能力演化为可自主使用工具的智能体雏形。",
    tags: ["推理", "智能体"],
    url: '',
    source: "https://openai.com/index/introducing-o3-and-o4-mini/",
  },
  {
    date: "2025-04-28",
    title: "Qwen3 开源",
    text: "阿里巴巴开源 Qwen3 系列，从 0.6B 到 235B（MoE）共八款，首次在开源模型中支持思考与非思考模式切换，全部 Apache 2.0 许可，进一步扩大中国开源阵营份额。",
    tags: ["开源", "中国"],
    url: '',
    source: "https://qwenlm.github.io/blog/qwen3/",
  },
  {
    date: "2025-05-22",
    title: "Claude 4 发布",
    text: "Anthropic 发布 Claude Opus 4 与 Sonnet 4，主打长时间自主编码与工具使用，可连续工作数小时，被广泛用于编程智能体，把竞争焦点从答题转向完成真实任务。",
    tags: ["模型", "智能体"],
    url: '',
    source: "https://www.anthropic.com/news/claude-4",
  },
  {
    date: "2025-07-09",
    title: "Grok 4 发布",
    text: "xAI 发布 Grok 4，宣称用十万级 GPU 训练并强化推理能力，同时在 X 平台全量开放。它是马斯克阵营进入前沿梯队的关键节点，也把训练算力规模推向新量级。",
    tags: ["模型", "推理"],
    url: '',
    source: "https://x.ai/news/grok-4",
  },
  {
    date: "2025-07-11",
    title: "Kimi K2 开源",
    text: "月之暗面开源万亿参数 MoE 模型 Kimi K2，激活参数 32B，专为智能体工具调用调优，在开源模型中首次取得领先的代理能力，成为中国开源模型的高光时刻。",
    tags: ["开源", "智能体"],
    url: '',
    source: "https://github.com/MoonshotAI/Kimi-K2",
  },
  {
    date: "2025-07-29",
    title: "GLM-4.5 发布",
    text: "智谱发布并开源 GLM-4.5，355B 参数 MoE、MIT 许可，把推理、编程与智能体能力整合进单一模型，在中英文开源榜单上长期位居前列。",
    tags: ["中国", "开源"],
    url: '',
    source: "https://z.ai/blog/glm-4.5",
  },
  {
    date: "2025-08-07",
    title: "GPT-5 发布",
    text: "OpenAI 发布 GPT-5，把快速回答与深度推理统一到一个系统，自动按问题难度分配思考量，并大幅降低幻觉。它标志着推理能力从独立模型回归通用主力模型。",
    tags: ["模型", "里程碑"],
    url: '',
    source: "https://openai.com/index/introducing-gpt-5/",
  },
  {
    date: "2025-08-21",
    title: "DeepSeek-V3.1 发布",
    text: "DeepSeek 发布 V3.1，用一套权重同时支持思考与非思考两种模式，并针对智能体场景优化工具调用，成为此后中国开源模型普遍采用的双模式范式。",
    tags: ["中国", "智能体"],
    url: '',
    source: "https://api-docs.deepseek.com/news/news250821",
  },
  {
    date: "2025-11-18",
    title: "Gemini 3 发布",
    text: "Google 发布 Gemini 3 Pro 与 Deep Think，在推理、多模态与编程基准上全面领先，被普遍认为让 Google 重回前沿第一梯队，引发竞争对手加速迭代。",
    tags: ["模型", "里程碑"],
    url: '',
    source: "https://blog.google/products/gemini/gemini-3/",
  },
  {
    date: "2025-12-01",
    title: "DeepSeek-V3.2 发布",
    text: "DeepSeek 发布 V3.2 与 V3.2-Speciale，采用自研稀疏注意力（DSA）降低长上下文成本，并在 IMO、ICPC 等竞赛中取得金牌级成绩，继续以效率路线冲击前沿。",
    tags: ["中国", "开源"],
    url: '',
    source: "https://api-docs.deepseek.com/news/news251201",
  },
  {
    date: "2026-01-27",
    title: "Kimi K2.5 发布",
    text: "月之暗面发布 Kimi K2.5，在 K2 基础上加入原生视觉理解，并支持「智能体集群」同时调度上百个子代理协作，把开源模型的能力重心推向多模态与多智能体。",
    tags: ["中国", "多模态"],
    url: '',
    source: "https://huggingface.co/moonshotai/Kimi-K2.5",
  },
  {
    date: "2026-02-11",
    title: "GLM-5 发布",
    text: "智谱发布旗舰模型 GLM-5，744B 参数 MoE、激活约 40B，以 MIT 许可开源，在编程与智能体任务上对标国际一线闭源模型，被视为中国开源模型的又一次追赶突破。",
    tags: ["中国", "开源"],
    url: '',
    source: "https://www.reuters.com/technology/chinas-ai-startup-zhipu-releases-new-flagship-model-glm-5-2026-02-11/",
  },
  {
    date: "2026-02-15",
    title: "Qwen3.5 开源",
    text: "阿里巴巴开源 Qwen3.5，397B MoE 架构并原生多模态，主打高性价比推理，面向智能体场景优化，继续稳固 Qwen 在全球开源模型下载与调用量上的领先位置。",
    tags: ["中国", "开源"],
    url: '',
    source: "https://home.alibabagroup.com/en-US/document-1960233590314762240",
  },
  {
    date: "2026-04-16",
    title: "Claude Opus 4.7 发布",
    text: "Anthropic 发布 Claude Opus 4.7，重点提升高难度软件工程能力与图像分辨率，并首次为网络能力配套分级管控，成为当时编程类评测中最强的模型之一。",
    tags: ["模型", "智能体"],
    url: '',
    source: "https://www.anthropic.com/news/claude-opus-4-7",
  },
  {
    date: "2026-04-23",
    title: "GPT-5.5 发布",
    text: "OpenAI 发布 GPT-5.5，在智能体编程、科学推理与知识工作上全面增强，同时显著提高 token 效率，被视为当年闭源阵营的能力基准线。",
    tags: ["模型", "智能体"],
    url: '',
    source: "https://openai.com/index/introducing-gpt-5-5/",
  },
  {
    date: "2026-04-24",
    title: "DeepSeek-V4 预览",
    text: "DeepSeek 发布并开源 V4 预览版，V4-Pro 为 1.6T 总参数、49B 激活，把 100 万 token 上下文设为默认，并主打智能体编程，标志中国开源模型进入万亿参数时代。",
    tags: ["中国", "开源"],
    url: '',
    source: "https://www.deepseek.com/en/news/v4-preview/",
  },
  {
    date: "2026-06-01",
    title: "MiniMax M3 发布",
    text: "MiniMax 发布 M3，采用自研稀疏注意力 MSA，是首个同时具备前沿编程能力、百万上下文与原生多模态的开源权重模型，并支持操作桌面电脑完成长链路任务。",
    tags: ["中国", "开源"],
    url: '',
    source: "https://www.minimax.io/blog/minimax-m3",
  },
  {
    date: "2026-06-09",
    title: "Claude Fable 5 发布",
    text: "Anthropic 发布 Mythos 级模型 Claude Fable 5，能力超过此前所有公开模型，并配套分级安全分类器；同期向政府与安全机构提供解除部分限制的 Claude Mythos 5。",
    tags: ["模型", "里程碑"],
    url: '',
    source: "https://www.anthropic.com/news/claude-fable-5-mythos-5",
  },
  {
    date: "2026-06-13",
    title: "GLM-5.2 发布",
    text: "智谱推出 GLM-5.2，用自研 IndexShare 稀疏注意力把上下文扩展到 100 万 token，并以 MIT 许可开放 753B 的 MoE 权重，长程编程与智能体评测成绩大幅提升。",
    tags: ["中国", "开源"],
    url: '',
    source: "https://z.ai/blog/glm-5.2",
  },
  {
    date: "2026-07-09",
    title: "GPT-5.6 发布",
    text: "OpenAI 发布 GPT-5.6 家族，分 Luna、Terra、Sol 三档，主打 token 效率与网络安全能力。此前曾因政府要求推迟公开发布，前沿模型的发布节奏首次受到监管直接影响。",
    tags: ["模型", "智能体"],
    url: '',
    source: "https://openai.com/index/gpt-5-6/",
  },
  {
    date: "2026-07-16",
    title: "Kimi K3 开源",
    text: "月之暗面发布 Kimi K3，2.8T 参数，采用 Kimi Delta Attention 与注意力残差，支持百万上下文与原生视觉，是全球首个开源的 3T 级模型，并承诺随后放出权重。",
    tags: ["中国", "开源"],
    url: '',
    source: "https://www.kimi.ai/blog/kimi-k3",
  },
  {
    date: "2026-07-16",
    title: "Grok 4.5 发布",
    text: "xAI 发布 Grok 4.5，与 Cursor 联合训练，主打编程与智能体任务，token 效率较同级模型高出数倍，定价大幅下调，把前沿模型之间的价格战推向新阶段。",
    tags: ["中国", "开源"],
    url: '',
    source: "https://x.ai/news/grok-4-5",
  },
  {
    date: "2026-09-03",
    title: "GPT-6 Astra 发布",
    text: "OpenAI 发布 GPT-6 Astra，称其开启 AGI 时代，可像人一样操作电脑完成报税、购物等任务，是首个在超十万张 GPU 上预训练的模型，但因网络能力过强而分批放开。",
    tags: ["模型", "里程碑"],
    url: '',
    source: "https://openai.com/index/gpt-6-astra/",
  },
  {
    date: "2026-09-10",
    title: "DeepSeek V4.1 Flash 发布",
    text: "DeepSeek 发布 V4.1-Flash，552B MoE、非对称编解码架构，输入仅 8B、输出 16B 激活，具备原生视觉理解，KV 缓存降至前代四分之一，进一步压低智能体推理成本。",
    tags: ["中国", "多模态"],
    url: '',
    source: "https://api-docs.deepseek.com/news/news260910",
  },
];
